// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Node =
  | { type: "result"; data: string }
  // NOTE: the data field is serialized as a Goal<'_, Predicate<'_>>
  // Or, rather, it should be but the backend is pooping out right now.
  // | { type: "goal", data: any, }
  | { type: "goal"; data: string }
  | { type: "candidate"; data: string };
