// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { Candidate } from "./Candidate";

export type Node =
  | { type: "result"; data: string }
  // NOTE: the data field is serialized as a Goal<'_, Predicate<'_>>
  | { type: "goal"; data: any }
  | { type: "candidate"; data: Candidate };
