// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharRange } from "./CharRange";
import type { ObligationKind } from "./ObligationKind";

export type Obligation = { range: CharRange, data: any, kind: ObligationKind };