// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharRange } from "./CharRange";
import { ObligationHash } from "./ObligationHash";
import type { ObligationKind } from "./ObligationKind";
import type { ObligationNecessity } from "./ObligationNecessity";

export type Obligation = {
  range: CharRange;
  predicate: any;
  hash: ObligationHash;
  kind: ObligationKind;
  necessity: ObligationNecessity;
  result: "yes" | "maybe-overflow" | "maybe-ambiguity" | "no";
  isSynthetic: boolean;
};
