// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Node } from "./Node";
import type { TreeTopology } from "./TreeTopology";

export interface SerializedTree { root: number, nodes: Array<Node>, topology: TreeTopology<number>, errorLeaves: Array<number>, unnecessaryRoots: Array<number>, }