// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { Canonical } from '../../../types';
import { Substitution } from '../../../types';

export type Guidance = { Definite: Canonical<Substitution> } | { Suggested: Canonical<Substitution> } | "Unknown";