// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { OpaqueTy } from '../../../types';
import { ProjectionTy } from '../../../types';

export type AliasTy = { Projection: ProjectionTy } | { Opaque: OpaqueTy };