// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { Interner } from '../../../types';
import { VariableKinds } from '../../../types';

export interface Binders<T> { binders: VariableKinds, value: T, }