// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { CanonicalVarKinds } from '../../../types';
import { Interner } from '../../../types';

export interface Canonical<T> { value: T, binders: CanonicalVarKinds, }