// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { ConstScalar } from '../../../types';

export interface ConcreteConst { interned: ConstScalar, }