// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { Lifetime } from '../../../types';
import { Ty } from '../../../types';

export type Constraint = { LifetimeOutlives: [Lifetime, Lifetime] } | { TypeOutlives: [Ty, Lifetime] };