// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { ConstValue } from '../../../types';
import { Ty } from '../../../types';

export interface ConstData { ty: Ty, value: ConstValue, }