// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { BoundVar } from '../../../types';
import { ConcreteConst } from '../../../types';
import { InferenceVar } from '../../../types';
import { PlaceholderIndex } from '../../../types';

export type ConstValue = { BoundVar: BoundVar } | { InferenceVar: InferenceVar } | { Placeholder: PlaceholderIndex } | { Concrete: ConcreteConst };