// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { Constraints } from '../../../types';
import { Substitution } from '../../../types';

export interface ConstrainedSubst { subst: Substitution, constraints: Constraints, }