// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { Constraint, InEnvironment } from '../../../types';

export interface Constraints { interned: InEnvironment<Constraint>[], }