// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { Binders } from '../../../types';
import { Lifetime } from '../../../types';
import { QuantifiedWhereClauses } from '../../../types';

export interface DynTy { bounds: Binders<QuantifiedWhereClauses>, lifetime: Lifetime, }