// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { GenericArg } from '../../../types';

export interface EqGoal { a: GenericArg, b: GenericArg, }