// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { FnSig } from '../../../types';
import { FnSubst } from '../../../types';

export interface FnPointer { num_binders: number, sig: FnSig, substitution: FnSubst, }