// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { Const } from '../../../types';
import { Lifetime } from '../../../types';
import { Ty } from '../../../types';

export type GenericArgData = { Ty: Ty } | { Lifetime: Lifetime } | { Const: Const };