// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { Environment } from '../../../types';
import { Interner } from '../../../types';

export interface InEnvironment<G> { environment: Environment, goal: G, }