// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { BoundVar } from '../../../types';
import { InferenceVar } from '../../../types';
import { PlaceholderIndex } from '../../../types';
import { Void } from '../../../types';

export type LifetimeData = { BoundVar: BoundVar } | { InferenceVar: InferenceVar } | { Placeholder: PlaceholderIndex } | "Static" | "Erased" | { Phantom: [Void] };