// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { Lifetime } from '../../../types';

export interface LifetimeOutlives { a: Lifetime, b: Lifetime, }