// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { OpaqueTyId } from '../../../types';
import { Substitution } from '../../../types';

export interface OpaqueTy { opaque_ty_id: OpaqueTyId, substitution: Substitution, }