// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import { ProgramClause } from "./ProgramClause";

export interface ProgramClauses { interned: ProgramClause[], }