// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { Binders } from '../../../types';
import { ProgramClauseImplication } from '../../../types';

export type ProgramClauseData = Binders<ProgramClauseImplication>;