// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { AssocTypeId } from '../../../types';
import { Substitution } from '../../../types';

export interface ProjectionTy { associated_ty_id: AssocTypeId, substitution: Substitution, }