// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { FloatTy } from '../../../types';
import { IntTy } from '../../../types';
import { UintTy } from '../../../types';

export type Scalar = "Bool" | "Char" | { Int: IntTy } | { Uint: UintTy } | { Float: FloatTy };