// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { Canonical } from '../../../types';

export interface UCanonical<T> { canonical: Canonical<T>, universes: number, }