// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import { VariableKind } from "./VariableKind";

export interface VariableKinds { interned: VariableKind[], }