// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { Ty } from '../../../types';
import { TyVariableKind } from '../../../types';

export type VariableKind = { Ty: TyVariableKind } | "Lifetime" | { Const: Ty };