// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { AliasEq } from '../../../types';
import { LifetimeOutlives } from '../../../types';
import { TraitRef } from '../../../types';
import { TypeOutlives } from '../../../types';

export type WhereClause = { Implemented: TraitRef } | { AliasEq: AliasEq } | { LifetimeOutlives: LifetimeOutlives } | { TypeOutlives: TypeOutlives };