// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { ConstId } from '../../../types';
import { FunctionId } from '../../../types';
import { TypeAliasId } from '../../../types';

export type AssocItemId = { FunctionId: FunctionId } | { ConstId: ConstId } | { TypeAliasId: TypeAliasId };