// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { BuiltinFloat } from '../../../types';
import { BuiltinInt } from '../../../types';
import { BuiltinUint } from '../../../types';

export type BuiltinType = "Char" | "Bool" | "Str" | { Int: BuiltinInt } | { Uint: BuiltinUint } | { Float: BuiltinFloat };