// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { EnumId } from '../../../types';
import { StructId } from '../../../types';
import { UnionId } from '../../../types';

export type ConcreteAdtId = { StructId: StructId } | { UnionId: UnionId } | { EnumId: EnumId };