// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { ConstId } from '../../../types';
import { EnumVariantId } from '../../../types';
import { FunctionId } from '../../../types';
import { InTypeConstId } from '../../../types';
import { StaticId } from '../../../types';

export type DefWithBodyId = { FunctionId: FunctionId } | { StaticId: StaticId } | { ConstId: ConstId } | { InTypeConstId: InTypeConstId } | { VariantId: EnumVariantId };