// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { EnumId } from '../../../types';

export interface EnumVariantId { parent: EnumId, }