// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { ConstBlockId } from '../../../types';
import { ConstId } from '../../../types';
import { InTypeConstId } from '../../../types';

export type GeneralConstId = { ConstId: ConstId } | { ConstBlockId: ConstBlockId } | { InTypeConstId: InTypeConstId };