// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { ConcreteAdtId } from '../../../types';
import { ConcreteImplId } from '../../../types';
import { ConcreteTraitId } from '../../../types';
import { ConstId } from '../../../types';
import { EnumVariantId } from '../../../types';
import { FunctionId } from '../../../types';
import { TraitAliasId } from '../../../types';
import { TypeAliasId } from '../../../types';

export type GenericDefId = { FunctionId: FunctionId } | { AdtId: ConcreteAdtId } | { TraitId: ConcreteTraitId } | { TraitAliasId: TraitAliasId } | { TypeAliasId: TypeAliasId } | { ImplId: ConcreteImplId } | { EnumVariantId: EnumVariantId } | { ConstId: ConstId };