// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { ConstParamId } from '../../../types';
import { LifetimeParamId } from '../../../types';
import { TypeParamId } from '../../../types';

export type GenericParamId = { TypeParamId: TypeParamId } | { ConstParamId: ConstParamId } | { LifetimeParamId: LifetimeParamId };