// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { ConcreteImplId } from '../../../types';
import { ConcreteTraitId } from '../../../types';
import { ExternBlockId } from '../../../types';
import { ModuleId } from '../../../types';

export type ItemContainerId = { ExternBlockId: ExternBlockId } | { ModuleId: ModuleId } | { ImplId: ConcreteImplId } | { TraitId: ConcreteTraitId };