// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { Macro2Id } from '../../../types';
import { MacroRulesId } from '../../../types';
import { ProcMacroId } from '../../../types';

export type MacroId = { Macro2Id: Macro2Id } | { MacroRulesId: MacroRulesId } | { ProcMacroId: ProcMacroId };