// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { BuiltinType } from '../../../types';
import { ConcreteAdtId } from '../../../types';
import { ConcreteTraitId } from '../../../types';
import { ConstId } from '../../../types';
import { EnumVariantId } from '../../../types';
import { FunctionId } from '../../../types';
import { MacroId } from '../../../types';
import { ModuleId } from '../../../types';
import { StaticId } from '../../../types';
import { TraitAliasId } from '../../../types';
import { TypeAliasId } from '../../../types';

export type ModuleDefId = { ModuleId: ModuleId } | { FunctionId: FunctionId } | { AdtId: ConcreteAdtId } | { EnumVariantId: EnumVariantId } | { ConstId: ConstId } | { StaticId: StaticId } | { TraitId: ConcreteTraitId } | { TraitAliasId: TraitAliasId } | { TypeAliasId: TypeAliasId } | { BuiltinType: BuiltinType } | { MacroId: MacroId };