// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { BlockId } from '../../../types';

export interface ModuleId { block: BlockId | null, }