[workspace]
members = [ "crates/*" ]
exclude = [ "crates/argus_cli/tests/workspaces", "examples" ]
resolver = "2"

[profile.dev.package.similar]
opt-level = 3

[patch.crates-io]
rustc_plugin = { git = "https://github.com/gavinleroy/rustc-plugin.git", branch = "unsafe-updates" }
rustc_utils = { git = "https://github.com/gavinleroy/rustc-plugin.git", branch = "unsafe-updates" }
