[workspace]
members = ["crates/*"]
exclude = ["crates/argus-cli/tests/workspaces", "examples"]
resolver = "2"

[workspace.dependencies]
log = "0.4"
anyhow = "1.0.75"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.108"
rustc_utils = { git = "https://github.com/DJMcNab/rustc_plugin", rev = "70646a67a5591b48a275a7e97cd5f63ff4cf873c" }
fluid-let = "1.0.0"
itertools = "0.14.0"

[profile.dev.package.similar]
opt-level = 3
