[config]
skip_core_tasks = true
default_to_workspace = false

[env]
PATH = "${PATH}:${PWD}/scripts"

# #################### #
# Binding initializers #
# #################### #

[tasks.init-bindings-lib]
command = "cargo"
args = ["test", "-p", "argus-lib", "--lib", "export_bindings", "--locked"]

[tasks.init-bindings-ser]
command = "cargo"
args = ["test", "-p", "argus-ser", "--locked"]

[tasks.init-bindings]
dependencies = ["init-bindings-lib", "init-bindings-ser"]
command = "ts-rs.scm"

[tasks.evaluation-node]
command = "node"
args = ["ide/packages/evaluation/dist/evaluation.cjs", "-s", "./data", "${@}"]

# #################### #
#       Builders       #
# #################### #

[tasks.build-back]
command = "cargo"
args = ["install", "--path", "crates/argus-cli", "--locked"]

# TODO: is there a way to set a command specific environment variable?
#       The below will make the configuration global...
# [env]
# CARGO_MAKE_WORKING_DIRECTORY = "ide"
[tasks.build-ide]
script = """
cd ide && depot build
"""

[tasks.build.run_task]
name = ["build-back", "build-ide"]
parallel = true

[tasks.watch-back]
script = """
cargo watch -i frontend -x 'install --path crates/argus-cli ${@}'
"""

[tasks.watch.run_task]
name = ["watch-back"]
parallel = true

# ############### #
# Evaluation Crap #
# ############### #

[tasks.eval]
command = "node"
args = ["ide/packages/evaluation/dist/evaluation.cjs", "-h", "${@}"]
dependencies = ["build"]

[tasks.eval-init]
command = "node"
args = ["ide/packages/evaluation/dist/evaluation.cjs", "-s", "./data", "${@}"]
dependencies = ["build"]

[tasks.eval-serve]
script = """
python3 -m webbrowser http://localhost:8080/eval
evaluation.scm
"""

[tasks.evaluation]
dependencies = ["evaluation-init", "evaluation-serve"]
