[config]
skip_core_tasks = true
default_to_workspace = false

[tasks.watch-front]
script = "cargo watch -i frontend -x 'install --path crates/argus_cli'"

[tasks.watch-front-debug]
script = "cargo watch -i frontend -x 'install --path crates/argus_cli --frozen --offline --debug'"

[tasks.watch.run_task]
name = ["watch-front"]
parallel = true

[tasks.init-bindings]
script = """
cargo test -p argus-lib --lib export_bindings --locked
./scripts/ts-rs.scm
"""

[tasks.evaluation]
script = """
cd ide && depot build && cd ..
node ide/packages/evaluation/dist/evaluation.cjs ./data
python3 -m webbrowser http://localhost:8080/eval
./scripts/evaluation.scm
"""
