[config]
skip_core_tasks = true
default_to_workspace = false

# #################### #
# Binding initializers #
# #################### #

[tasks.init-bindings-lib]
command = "cargo"
args = [
  "test", "-p", "argus-lib", "--lib", "export_bindings", "--locked"
]

[tasks.init-bindings-ser]
command = "cargo"
args = ["test", "-p", "argus-ser", "--locked"]

[tasks.init-bindings]
command = "./scripts/ts-rs.scm"
dependences = ["tasks.init-bindings-lib", "tasks.init-bindings-ser"]

[tasks.evaluation-node]
command = "node"
args = ["ide/packages/evaluation/dist/evaluation.cjs", "-s", "./data", "${@}"]

# #################### #
#       Builders       #
# #################### #

[tasks.build-back]
command = "cargo"
args = [
  "install", "--path", "crates/argus-cli", "--locked", 
]

# TODO: is there a way to set a command specific environment variable?
#       The below will make the configuration global...
# [env]
# CARGO_MAKE_WORKING_DIRECTORY = "ide"
[tasks.build-ide]
script = """
cd ide && depot build
"""

[tasks.build.run_task]
name = ["build-back", "build-ide"]
parallel = true

[tasks.watch-back]
command = "cargo"
args = [	
  "watch", 
  "-i", 
  "frontend", 
  "-x", 
  "'install", "--path", "crates/argus-cli", "${@}", "'", 
]

[tasks.watch.run_task]
name = ["watch-back"]
parallel = true

# ############### #
# Evaluation Crap #
# ############### #

[tasks.evaluate-inertia]
command = "node"
args = ["ide/packages/evaluation/dist/evaluation.cjs", "-h", "${@}"]
dependencies = ["build"]

[tasks.evaluation-init]
command = "node"
args = ["ide/packages/evaluation/dist/evaluation.cjs", "-s", "./data", "${@}"]
dependencies = ["build"]

[tasks.evaluation-serve]
script = """
python3 -m webbrowser http://localhost:8080/eval
./scripts/evaluation.scm
"""

[tasks.evaluation]
dependencies = ["evaluation-init", "evaluation-serve"]
