name: setup
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - uses: davidB/rust-cargo-make@v1
      with:
        version: '0.36.4'

    - name: Install Guile
      run: sudo apt-get install -y guile-3.0
      shell: bash

    - name: Install Depot
      run: cargo install --git https://github.com/cognitive-engineering-lab/depot.git --locked depot-js && depot setup
      shell: bash

    - name: Install Test Libraries
      run: sudo apt-get install -y libasound2-dev libudev-dev
      shell: bash

    - name: Gen bindings
      run: cargo make init-bindings
      shell: bash

    - name: Prepare IDE
      run: cd ide && depot build
      shell: bash

    - name: Install Argus
      run: cargo install --path crates/argus-cli --debug --locked
      shell: bash
