name: setup
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - uses: davidB/rust-cargo-make@v1
      with:
        version: '0.36.4'

    - name: Install Guile
      run: sudo apt-get install -y guile-3.0
      shell: bash

    - name: Install Depot
      run: curl https://raw.githubusercontent.com/cognitive-engineering-lab/depot/main/scripts/install.sh | sh -s e92a63edcb17cf156e399587b79192369911560e
      shell: bash

    - name: Install Test Libraries
      run: sudo apt-get install -y libasound2-dev libudev-dev
      shell: bash

    - name: Gen bindings
      run: cargo make init-bindings
      shell: bash

    - name: Prepare IDE
      run: cd ide && depot build
      shell: bash

    - name: Install Argus
      run: cargo install --path crates/argus_cli --debug --locked
      shell: bash
