[package]
name = "argus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc_utils = { version = "0.7.3-nightly-2023-11-08", features = ["serde", "ts-rs"] }

log = "0.4"
index_vec = { version = "0.1.3", features = ["serde"] }
serde = { version = "1.0.192", features = ["derive"] }
smallvec = "1.11.2"
ts-rs = { version = "6.2.0", features = [
    "rustc-hash-impl",
    "index-vec-impl"
] }
anyhow = "1.0.75"
fluid-let = "1.0.0"
itertools = "0.12.0"
