// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { ClauseKind } from '../../../types';
import { ProgramClause } from '../../../types';

export interface ConsideredClause { clause: ProgramClause, could_match: boolean, kind: ClauseKind, }