// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { Binders } from '../../../types';
import { DomainGoal } from '../../../types';
import { Goal } from '../../../types';
import { InEnvironment } from '../../../types';
import { ProgramClauseImplication } from '../../../types';

export type FulfillmentKind = { WithClause: { goal: InEnvironment<DomainGoal>, clause: Binders<ProgramClauseImplication>, } } | { WithSimplification: { goal: InEnvironment<Goal>, } };