// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { FulfillFailKind } from '../../../types';
import { FulfillmentKind } from '../../../types';
import { InterimGoal } from '../../../types';
import { NoSolution } from '../../../types';
import { Solution } from '../../../types';
import { Substitution } from '../../../types';
import { Unification } from '../../../types';

export interface Fulfillment { solution: Solution | NoSolution | null, did_fail: FulfillFailKind, root_kind: FulfillmentKind, subst: Substitution, interim_goals: Array<InterimGoal>, unifications: Array<Unification>, obligations: Array<number>, }