// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { Environment } from '../../../types';
import { Goal } from '../../../types';

export interface InterimGoal { goal: Goal, environment: Environment, }