// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { Solution } from '../../../types';

export type LeafKind = { Resolved: Solution } | "UnificationSuccess" | "NoSolution" | "Floundered" | "Halted";