// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { LeafKind } from '../../../types';
import { NoSolution } from '../../../types';
import { Solution } from '../../../types';

export interface Leaf { outcome: Solution | NoSolution, kind: LeafKind, }