// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { Obligation } from '../../../types';
import { ObligationResult } from '../../../types';

export interface ObligationNode { obligation: Obligation, result: Array<ObligationResult>, }