// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { Goal } from '../../../types';
import { InEnvironment } from '../../../types';
import { ObligationKind } from '../../../types';
import { Substitution } from '../../../types';

export interface Obligation { goal: InEnvironment<Goal>, subst: Substitution, kind: ObligationKind, }