// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { NegativeSolution } from '../../../types';
import { NoSolution } from '../../../types';
import { PositiveSolution } from '../../../types';

export type OblResultKind = { Positive: PositiveSolution | NoSolution } | { Negative: NegativeSolution | NoSolution };