// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { GenericArg } from '../../../types';
import { Solution } from '../../../types';
import { UniverseMap } from '../../../types';

export interface PositiveSolution { free_vars: Array<GenericArg>, universes: UniverseMap, solution: Solution, }