// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { Fulfillment } from '../../../types';
import { Leaf } from '../../../types';
import { ObligationNode } from '../../../types';
import { SolveFromClauses } from '../../../types';

export type ProofTree = { FromClauses: SolveFromClauses } | { Fulfill: Fulfillment } | { Obligation: ObligationNode } | { Leaf: Leaf };