// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { ProofTree } from '../../../types';
import { TreeDescription } from '../../../types';
import { TreeTopology } from '../../../types';

export interface ProofTreeNav { descr: TreeDescription, nodes: Array<ProofTree>, topology: TreeTopology<number>, }