// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

type Idx = string | number | symbol;

export interface TreeTopology<I extends Idx> { children: Record<I, Array<I>>, parent: Record<I, I>, }