// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { Environment } from '../../../types';
import { UnifyKind } from '../../../types';
import { Variance } from '../../../types';

export interface Unification { environment: Environment, variance: Variance, kind: UnifyKind, }