// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { DomainGoal } from '../../../types';
import { GenericArg } from '../../../types';
import { Ty } from '../../../types';

export type UnifyKind = { GenericArg: [GenericArg, GenericArg] } | { Ty: [Ty, Ty] } | { DomainGoal: [DomainGoal, DomainGoal] };