// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharRange } from "./CharRange";
import type { ObligationHash } from "./ObligationHash";
import type { ObligationKind } from "./ObligationKind";
import type { ObligationNecessity } from "./ObligationNecessity";

export interface Obligation { obligation: any, hash: ObligationHash, range: CharRange, kind: ObligationKind, necessity: ObligationNecessity, result: EvaluationResult, isSynthetic: boolean, }