// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharRange } from "./CharRange";

export type Obligation = ({ type: "Success" } | { type: "Failure" }) & {
  range: CharRange;
  data: any;
  hash: string;
};
