// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Node } from "./Node";
import type { ProofCycle } from "./ProofCycle";
import type { ProofNodeIdx } from "./ProofNodeIdx";
import type { TreeTopology } from "./TreeTopology";

export interface SerializedTree { root: ProofNodeIdx, nodes: Array<Node>, topology: TreeTopology, errorLeaves: Array<ProofNodeIdx>, unnecessaryRoots: Array<ProofNodeIdx>, cycle?: ProofCycle, }