// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProofNodeIdx } from "./ProofNodeIdx";

export interface TreeTopology { children: Record<ProofNodeIdx, Array<ProofNodeIdx>>, parent: Record<ProofNodeIdx, ProofNodeIdx>, }