name: tests

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - uses: cachix/cachix-action@v16
        with:
          name: ${{ vars.CACHIX_CACHE_NAME }}
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - uses: mxschmitt/action-tmate@v3

      - name: Argus Test
        run: |
          nix develop .#ci -L --command ci-check
          cachix watch-store ${{ vars.CACHIX_CACHE_NAME }}

      - name: Test Build
        timeout-minutes: 20
        run: |
          nix build .#argus-extension -L
          cachix watch-store ${{ vars.CACHIX_CACHE_NAME }}
        

