name: tests

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - uses: cachix/cachix-action@v16
        with:
          name: ${{ vars.CACHIX_CACHE_NAME }}
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Argus Test
        run: |
          nix develop .#ci -L --command ci-check
          nix path-info --all | cachix push ${{ vars.CACHIX_CACHE_NAME }}

      - name: Test Build
        timeout-minutes: 20
        run: |
          nix build .#argus-extension -L
          nix path-info --all | cachix push ${{ vars.CACHIX_CACHE_NAME }}
        

