name: tests

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Test Build
        run: cachix watch-exec ${{ vars.CACHIX_CACHE_NAME }} -- nix build .#argus-ide -L
        
      - name: Argus Test
        run: nix develop .#ci -L --command ci-check

