name: tests

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            arch: x86_64
            output_name: amd64
          - os: ['self-hosted', 'ARM64']
            arch: aarch64
            output_name: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: ${{ vars.CACHIX_CACHE_NAME }}
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Smokescreen Build Tests
        run : |
          echo "Caching to ${{ vars.CACHIX_CACHE_NAME }}"
          nix build .#argus-extension -L &&
          cachix push ${{ vars.CACHIX_CACHE_NAME }} &&
          nix build .#argus-cli -L &&
          cachix push ${{ vars.CACHIX_CACHE_NAME }}

      - name: Argus Test
        run: nix develop .#ci -L --command ci-check
