name: merge

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - uses: cachix/cachix-action@v16
        with:
          name: ${{ vars.CACHIX_CACHE_NAME }}
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Cache Build
        run: nix build .#argus-extension -L
      - name: Cache
        run: cachix push ${{ vars.CACHIX_CACHE_NAME }} result 

