name: merge

on:
  push:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm] # macos-15
    runs-on: ${{ matrix.os }}
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - uses: cachix/cachix-action@v16
        with:
          name: ${{ vars.CACHIX_CACHE_NAME }}
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build & Cache
        run: |
          nix build .#argus-extension -L
          nix path-info --all | cachix push ${{ vars.CACHIX_CACHE_NAME }}

