name: publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish-crates:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - run: nix develop .#ci --command ci-crate-pub ${{ secrets.CRATES_IO }}

  publish-ide:
    runs-on: ubuntu-22.04
    needs: publish-crates
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - run: nix develop .#ci --command ci-ext-pub ${{ secrets.VSCODE_MRKT }} ${{ secrets.OVSX_MRKT }}
