// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { QueryAttempt } from '../../../types';

export type AttemptKind = { Required: Array<QueryAttempt> } | { Try: QueryAttempt };