// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { Safety } from '../../../types';

export interface CallableSig { is_varargs: boolean, safety: Safety, }