// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { Goal } from '../../../types';
import { InEnvironment } from '../../../types';
import { Ty } from '../../../types';

export interface ObligationSource { source: Ty | null, goal: InEnvironment<Goal>, }