// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { TreeDescription } from '../../../types';
import { TreeTopology } from '../../../types';

export interface SerializedTree { descr: TreeDescription, nodes: Array<string>, error_leaves: Array<number>, topology: TreeTopology<number>, }