// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { AttemptKind } from '../../../types';
import { ObligationSource } from '../../../types';

export interface TracedTraitQuery { info: ObligationSource, kind: AttemptKind, }